# Generated by Django 3.1.5 on 2022-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(default=11, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(default=424, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=322424, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
