# Generated by Django 3.1.5 on 2022-08-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220716_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='City',
            field=models.CharField(default='alex', max_length=11),
        ),
    ]
